// Reduce the source's component CSS to a pure LAYOUT skeleton.
//
// The previous build shipped base.css whole, so the original site's visual
// identity survived and the "redesign" was a reskin of someone else's design.
// This strips every declaration that contributes to how the site LOOKS —
// colour, background, border, shadow, radius, typography, decoration — and
// keeps only what controls where boxes sit. The new system then supplies
// 100% of the visual language.
//
// Kept deliberately:
//   * geometry (display/position/grid/flex/gap/size/margin/padding/overflow)
//   * transform — frequently structural (translate(-50%) centring)
//   * the --ds-* custom properties, so `gap: var(--ds-space-md)` still resolves.
//     Every VISUAL --ds-* token is redefined by system.css, which loads later.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'dist', 'styles', 'base.css');
const OUT = path.join(ROOT, 'src', 'styles', 'layout.css');

let css = fs.readFileSync(SRC, 'utf8');
const before = css.length;

// 1. Drop @font-face wholesale — fonts are loaded from the <head> link.
let fontFaces = 0;
css = css.replace(/@font-face\s*\{[^}]*\}/gi, () => { fontFaces++; return ''; });

// Properties that make the site LOOK the way it does.
const VISUAL = new RegExp('^(' + [
  'color', 'background', 'background-[a-z-]+',
  'border', 'border-(?!.*(width|spacing|collapse)$)[a-z-]+', 'border-radius',
  'box-shadow', 'text-shadow', 'outline', 'outline-[a-z-]+',
  'font', 'font-[a-z-]+', 'line-height', 'letter-spacing', 'word-spacing',
  'text-transform', 'text-decoration', 'text-decoration-[a-z-]+', 'text-align',
  'text-wrap', 'text-indent', 'white-space',
  'opacity', 'filter', 'backdrop-filter', 'mix-blend-mode', 'background-blend-mode',
  'fill', 'stroke', 'stroke-[a-z-]+',
  'transition', 'transition-[a-z-]+', 'animation', 'animation-[a-z-]+',
  'content', 'list-style', 'list-style-type', 'list-style-image',
  'cursor', 'text-rendering', '-webkit-font-smoothing', '-moz-osx-font-smoothing',
  '-webkit-text-fill-color', '-webkit-background-clip', 'background-clip',
  'scrollbar-color', 'accent-color', 'caret-color',
].join('|') + ')$', 'i');

// Visual --ds-* tokens get dropped here AND redefined in system.css.
// Every custom property that carries an appearance value. --color-* and the
// platform's --body-font-* / --button-* / --headings_* families are the old
// palette and type scale; leaving them in let the previous look bleed through.
const VISUAL_VAR = new RegExp('^--(' + [
  'ds-(fade|primary|accent|ink|bg|surface|paper|warm|line|hairline|glass|grad|glow|grain|grid|shadow|scrim|inset|icon|success|warning|danger|opacity|r-|font|dur|ease)',
  'et-',
  'color-[a-z0-9-]*',
  'body-font-[a-z-]*',
  'button-(font|radius|padding)[a-z-]*',
  'headings?[_-][a-z0-9-]*',
  'sgen-acc-[a-z-]*',
].join('|') + ')', 'i');

let dropped = 0, kept = 0;
const droppedProps = {};

// Walk declaration blocks, filtering declarations inside each.
css = css.replace(/\{([^{}]*)\}/g, (whole, body) => {
  const out = [];
  for (const raw of body.split(';')) {
    const decl = raw.trim();
    if (!decl) continue;
    const colon = decl.indexOf(':');
    if (colon < 0) { out.push(decl); continue; }
    const prop = decl.slice(0, colon).trim().toLowerCase();
    if (VISUAL.test(prop) || VISUAL_VAR.test(prop)) {
      dropped++;
      droppedProps[prop] = (droppedProps[prop] || 0) + 1;
      continue;
    }
    kept++;
    out.push(decl);
  }
  return '{' + (out.length ? out.join(';') + ';' : '') + '}';
});

// 3. Remove rules that are now empty, and empty media blocks they leave behind.
let emptyRules = 0;
let prev;
do {
  prev = css;
  css = css.replace(/[^{}]+\{\s*\}/g, () => { emptyRules++; return ''; });
  css = css.replace(/@media[^{]+\{\s*\}/gi, '');
  css = css.replace(/@supports[^{]+\{\s*\}/gi, '');
} while (css !== prev);

const header = `/* layout.css — the SOURCE's component CSS reduced to pure geometry.
 *
 * Generated by tools/strip-visuals.mjs from the crawled original. Every
 * declaration that contributed to how the old site LOOKED has been removed:
 * ${dropped} visual declarations and ${fontFaces} @font-face blocks dropped,
 * ${kept} layout declarations kept, ${emptyRules} rules emptied out.
 *
 * This file positions boxes. It must NOT be edited to add appearance —
 * all colour, surface, type and motion belongs in system.css.
 */
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + css);

console.log('layout.css written');
console.log('  in           ' + before + ' bytes');
console.log('  out          ' + (header.length + css.length) + ' bytes  (' + Math.round((1 - css.length / before) * 100) + '% smaller)');
console.log('  dropped      ' + dropped + ' visual declarations');
console.log('  kept         ' + kept + ' layout declarations');
console.log('  @font-face   ' + fontFaces + ' removed');
console.log('  emptied      ' + emptyRules + ' rules');
console.log('  top dropped  ' + Object.entries(droppedProps).sort((a, b) => b[1] - a[1]).slice(0, 14).map(([k, v]) => k + ':' + v).join(' '));
